### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ws-prive** [goatlas-io/atlas#19]
Hello,

I want to take a look at this, because we have an issue with getting the ingress working on grpc without envoy. However, the 
 Thanos part of Atlas is not clear to me. You do recommend to use the kube-prometheus-stack, but I am missing the Thanos server part. The kube-prometheus-stack doesn't have the Thanos server.

Can you clearify this for me? Which Thanos should I install and with options are mandatory?

Thanks!

**Comment by ekristen** [comment]
If you would like to see the entire project in action, I would recommend checking out the deploy script, but it requires a digital ocean account. 

The project was built with the `kube-prometheus-stack` in mind for all it's defaults, however it isn't required to use it. 

Atlas is designed to make connecting N+1 downstream clusters to an observability cluster where Thanos Query runs. The downstream cluster is where the Thanos Sidecars run.

When using `kube-prometheus-stack` you have to tell it to deploy the thanos components. On the observability cluster you are responsible for deploying the thanos query component.

The deployment process is mostly outlined here https://docs.goatlas.io/deployment/

Again the deploy script that uses digital ocean would be a good place to see the entire project deployed including all the yaml and manifests that get deployed to the clusters.

**Comment by Evantage-WS** [comment]
Hello @ekristen, thanks for the reply, I will look into this.

**Comment by Evantage-WS** [comment]
Hello @ekristen,

Just a couple of questions:
- Do we need the thanosService, the thanosServiceExternal or Ingress enabled or is just Envoy enough ?
- About the external IP in the config for a downstream cluster, is this the IP address from ie. eth0 on the Llnux host?

Thanks!

**Comment by ekristen** [comment]
If you are using the kube-prometheus-stack, you need to make sure that thanoService is enabled. You do not need thanosServiceExternal or the ingress.

The external IP for the downstream cluster is going to need be the IP address of an edge node/ingress where envoy will run when you deploy `atlas-envoy` to the downstream cluster.

**Comment by Evantage-WS** [comment]
Hello @ekristen 

Thanks, I will test it somewhere this week!

**Comment by Evantage-WS** [comment]
Hello @ekristen ,

Present, all the thanos sidecar data is send to the bucket via ingress on the central cluster to the minio-api. Is this something that also should be disabled? Thanks

**Comment by ekristen** [comment]
No not at all.

Atlas is about making the sidecar accessible from the observability cluster (or in your case the "central cluster").

There are two primary purposes for the sidecar, allowing thanos-query to query the sidecar in real-time for all data in the local prometheus instance (including metrics under the current 2 hour block threshold that haven't been uploaded) and second to ship the TSDB blocks to S3 every 2 hours when it rolls over.

**Comment by Evantage-WS** [comment]
Hi @ekristen ,

Thanks again, sorry, I do see I see my question was not clear. I meant that the ingress should be disabled, not the upload itself. When Envoy is in place, I can imagine that the upload of the sidecar data to the bucket on the central cluster can go thru this envoy proxy.

Sorry for all the questions!

**Comment by ekristen** [comment]
I understand what you are asking. No, atlas is not designed to route any of the s3 traffic from the sidecar.

**Comment by Evantage-WS** [comment]
Hi @ekristen,

Currently I have no time to look into this. sorry, I have to work on another project. Maybe in the second quarter of next year I will look into this. I just want to let you know this, appreciate your help.
